version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--providers.docker.network=psl-network"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - psl-network

  laravel-dev:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: laravel-dev
    restart: always
    env_file: .env.dev
    expose: ["9000"]
    volumes:
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - psl-network

  nginx-dev:
    image: nginx:stable-alpine
    container_name: nginx-dev
    restart: always
    depends_on:
      - laravel-dev
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
    networks:
      - psl-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel-dev.rule=Host(`api.dev.psl-app.dev`)"
      - "traefik.http.routers.laravel-dev.entrypoints=websecure"
      - "traefik.http.routers.laravel-dev.tls.certresolver=letsencrypt"
      - "traefik.http.routers.laravel-dev.service=nginx-dev-service"
      - "traefik.http.services.nginx-dev-service.loadbalancer.server.port=80"

  laravel-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: laravel-prod
    restart: always
    env_file: .env.prod
    expose: ["9000"]
    volumes:
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - psl-network

  nginx-prod:
    image: nginx:stable-alpine
    container_name: nginx-prod
    restart: always
    depends_on:
      - laravel-prod
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
    networks:
      - psl-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel-prod.rule=Host(`api.psl-app.dev`)"
      - "traefik.http.routers.laravel-prod.entrypoints=websecure"
      - "traefik.http.routers.laravel-prod.tls.certresolver=letsencrypt"
      - "traefik.http.routers.laravel-prod.service=nginx-prod-service"
      - "traefik.http.services.nginx-prod-service.loadbalancer.server.port=80"

networks:
  psl-network:
