version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--providers.docker.network=psl-network"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - psl-network

  laravel-dev:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: laravel-dev
    restart: always
    env_file: .env.dev
    expose: ["9000"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel-dev.rule=Host(`api.dev.psl-app.dev`)"
      - "traefik.http.routers.laravel-dev.entrypoints=websecure"
      - "traefik.http.routers.laravel-dev.tls.certresolver=letsencrypt"
      - "traefik.docker.network=psl-network"
    networks:
      - psl-network

  laravel-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: laravel-prod
    restart: always
    env_file: .env.prod
    expose: ["9000"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel-prod.rule=Host(`api.psl-app.dev`)"
      - "traefik.http.routers.laravel-prod.entrypoints=websecure"
      - "traefik.http.routers.laravel-prod.tls.certresolver=letsencrypt"
      - "traefik.docker.network=psl-network"
    networks:
      - psl-network

networks:
  psl-network:
